config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :comments
    end
  resources :users 

  get 'static_pages/about' 

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#about'

  resources :orders, only: [:index, :show, :create, :destroy]
  
  post 'static_pages/thank_you'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  post 'payments/create' => 'payments#create'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :comments
	has_many :orders


	def average_rating
	  comments.average(:rating).to_f
	end

	validates :name, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  #def index
  #  if params[:q]
  #    search_term = params[:q]
  #    @products = Product.where("name LIKE ?", "%#{search_term}%")
  #  else
  #    @products = Product.all
  #  end
  #end

  def index    
    if params[:q]
      search_term = params[:q]
      if Rails.env.production?
        @products = Product.where("name ilike ?", "%#{search_term}%")
      else
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      end
    else
      @products = Product.all
    end
  end 

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC")
    @comments = @product.comments.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @product = Product.new
    @products = Product.limit(3)
  end 
  

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/static_pages/landing_page", notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :latin_name, :price)
    end

    private

end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_carousel.html.erb
<!--image carousel --> 
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
  <div class="item<%= " active" if product == @products.first %>">
      <div class="carousel-imgage">
      <%= image_tag(product.image_url) %>
      </div>
      <div class="carousel-caption">
        <%= product.name %>
      </div>
        </div>
    <% end %>
  </div> 


    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row comments">
			    <p>
            <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
              <% if signed_in? && current_user.admin? %>
              <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </p>
          <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>    
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
  <%= f.label :latin_name %><br>
  <%= f.text_field :latin_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <%= form_for([@product, @product.comments.build], remote:true) do |f| %>
    <p>
      <%= f.text_area :body, class: "form-control", id:"comment_area", placeholder:"Write your review here" %>
    </p>
    <p>
      <%= f.label :rating %><br>
      <div class="rating"></div>  
    </p>

    <p>
      <%= f.submit 'Submit', class: 'btn btn-default' %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag(product.image_url, class: "owlimage") %>
    <% cache do %>   
      <div class="caption">
         <h2><%= link_to product.name, product %></h2>
           <p> <span class="glyphicon glyphicon-menu-right" area-hidden="true"></span><i><%= product.latin_name %></i></p>
           <p><span class="glyphicon glyphicon-menu-right" area-hidden="true"></span><%= product.description %></p>
           <p><span class="glyphicon glyphicon-menu-right" area-hidden="true"></span><%= product.colour %></p>
           <p> <span class="glyphicon glyphicon-tag" area-hidden="true"></span> € <%= product.price %></p>
           <p> <span class="glyphicon glyphicon-thumbs-up" area-hidden="true"></span> Tell others how awesome you owls is!
           </p>
      </div> <!--caption-->
    <% end %>   
    </div>
  </div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="titelproductpage">Waiting for new owners</h1>

<!--
<table class="producttable">
  <thead>
    <tr class="table">
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Colour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr class="table">
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.colour %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<div class="container-fluid">
  <div class="row">
   <% cache(cache_key_for_products) do %>
      <%= render @products %>
    <% end %>  
  </div>
</div>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <%= image_tag(@product.image_url, class: "img-zoom owlimage", data_zoom_image: @product.image_url) %>
    <div class="caption">
     <%cache @product do %> 
       <h2><%= @product.name %></h2>
         <p> <span class="glyphicon glyphicon-menu-right" area-hidden="true"></span><i><%= @product.latin_name %></i></p>
         <p><span class="glyphicon glyphicon-menu-right" area-hidden="true"></span><%= @product.description %></p>
         <p><span class="glyphicon glyphicon-menu-right" area-hidden="true"></span><%= @product.colour %></p>
         <p> <span class="glyphicon glyphicon-tag" area-hidden="true"></span> € <%= @product.price %></p>
       <%end%>  
         <div class= "av_comment row">
           <div class="col-sm-4 col-md-4">
             <p> <span class="glyphicon glyphicon-hand-right" area-hidden="true"> </span> Average rating</p> 
           </div>
           <div class="col-sm-8 col-md-8">  
             <div class="rated" data-score="<%= @product.average_rating %>"></div>
           </div>
         </div> 
         <div class="row">
           <div class="col-sm-4 col-md-4">
            <p> <span class="glyphicon glyphicon-hand-right" area-hidden="true"> </span> Get your owl here </p>
           </div>
           <div class="col-sm-4 col-md-4">
            <%= form_tag "/payments/create" do %>
             <%= render partial: "shared/stripe_checkout_button" %>
             <%= hidden_field_tag(:product_id, @product.id) %>
            <% end %>
           </div>
         </div>  
        <div class="leave_comment">
          <p class="pull-left"> <span class="glyphicon glyphicon-thumbs-up" area-hidden="true"></span> Tell others how awesome you owls is, leave a review!!
          </p>
          <div class="new_comment">
            <%= render 'new_comment' %>
          </div>  
        <div>
        <div>
          <%= render 'comments' %>
        </div>  
    </div> <!--caption-->
    <%= will_paginate @comments %>
  </div>
</div>

<div>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>
</div>