config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :comments
    end
  resources :users 

  get 'static_pages/about' 

  get 'static_pages/contact'

  get 'static_pages/index'

  root 'static_pages#about'

  resources :orders, only: [:index, :show, :create, :destroy]
  
  post 'static_pages/thank_you'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  post 'payments/create' => 'payments#create'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAppOne</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>

<!--navigation -->
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul>
        <li class="navbar-brand">
          <%=link_to "OWLS R'US", static_pages_about_path %>
        </li>
      </ul>
    </div>

    <!-- product and contact link -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active page-scroll"> <span class="sr-only">(current)</span>
          <%= link_to "Products", products_path %>
        </li>
        <li class="page-scroll">
      <%=link_to "Contact", static_pages_contact_path %>
        </li>
      </ul>

    <!--search field and btn-->
        <%= form_tag("/products", method: "get", :class=> "navbar-form navbar-right") do %>
          <%= text_field_tag(:q, "", class: "form-control selector", placeholder: "Find your owl") %>
          <%= submit_tag("Hit me!", class: "btn btn-default") %>
        <% end %>
      
      <!--login link-->
      <ul class="nav navbar-nav navbar-right">
        <li class="login">
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        <% else %>
          <%= link_to('Login', new_user_session_path) %>
        <% end %>          
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<!--flash notice tages. This block will display a welcome message when you login -->
  <% if notice %>
    <p id="notice" class=" alert alert-succes" role="alert">
      <%= notice %>
    </p>  
  <%end%>
  <%if alert %>  
    <p id="alert" class=" alert alert-danger" role="alert">
      <%= alert %>
    </p>
  <%end%>  

  <%= yield %>

  <footer>
    <p>Copyright &copy; owls R'Us</p>
  </footer>

</body>
</html>

app/views/layouts/navbar.html.erb
 	Navbar

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-2 visible-xs-block border">
          <a class="navbar-brand" href="#page-top">Owls R'us</a>  
      </div>
      <div class="col-xs-8 visible-xs-block border">
          <!-- hamburger menu -->
          <div class="navbar-header page-scroll">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
            </div> <!--closes navbar-header page scroll-->                        
            <!-- Collect the nav links, forms, and other content for toggling -->

            <div class="collapse navbar-collapse pull-left" id="bs-example-navbar-collapse-1">          
              <div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <%= link_to "Products", products_path %>
                    </li>
                    <li class="page-scroll">
                        <%= link_to "about", static_pages_about_path %> 
                    </li>
                    <li class="page-scroll">
                        <%=link_to "Contact", static_pages_contact_path %> 
                    </li>
                    <li class="login">
                      <% if user_signed_in? %>
                        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                      <% else %>
                        <%= link_to('Login', new_user_session_path) %>
                      <% end %>
                    </li>                    
                </ul>
              </div> 
            </div> <!-- /.navbar-collapse -->  
      </div> <!-- closes: "col-xs-8 visible-xs-block border"--> 
      <div class="col-xs-2 visible-xs-block border">
        <div class="search">
            <%= form_tag("/products", method: "get") do %>
            <form class="navbar-form" role="search">
                <ul class ="search">
                  <li><%= label_tag(:q, "Search for") %></li>
                  <li><%= text_field_tag (:q), class: "form-control", id:"search_area", placeholder:"Find your owl here"%></li>
                  <li><%= submit_tag "Search", class: 'btn btn-default navbar-btn' %></li> 
                  <% end %>
                </ul>
            </form>
          </div>    
      </div> <!--col-xs-2 visible-xs-block border-->
    <div class="col-sm-3 col-lg-3 visible-sm-block visible-md-block visible-lg-block border">
        <a class="navbar-brand" href="#page-top">Owls R'us</a>
      </div>
      <div class="col-sm-6 col-lg-6 visible-sm-block visible-md-block border visible-lg-block">
          <!-- hamburger menu -->
          <div class="navbar-header page-scroll">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
            </div> <!--closes navbar-header page scroll-->                        
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse pull-left" id="bs-example-navbar-collapse-1">          
              <div>
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <%= link_to "Products", products_path %>
                    </li>
                    <li class="page-scroll">
                        <%= link_to "about", static_pages_about_path %> 
                    </li>
                    <li class="page-scroll">
                        <%=link_to "Contact", static_pages_contact_path %> 
                    </li>
                    <li class="login">
                      <% if user_signed_in? %>
                        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                      <% else %>
                        <%= link_to('Login', new_user_session_path) %>
                      <% end %>
                    </li>                    
                </ul>
              </div> 
            </div> <!-- /.navbar-collapse -->  
      </div> <!-- closes: "col-xs-8 visible-xs-block border"-->
    <div class="col-sm-3 col-lg-3 visible-sm-block visible-md-block visible-lg-block border">
        <div class="search">
            <%= form_tag("/products", method: "get") do %>
            <form class="navbar-form" role="search">
              <div class="search">
                <%= label_tag(:q, "Search for") %>
                <%= text_field_tag(:q) %>
                <%= submit_tag "Search", class: 'btn btn-default navbar-btn' %> 
              </div>  
            </form>
            <% end %>
          </div>    
    </div> <!--closes: col-sm-3 visible-sm-block visible-md-block border-->
    </div>
  </div> 
</nav>